version: '3.7'
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - '9200:9200'
    networks:
      - bookmark
    environment:
      - discovery.type=single-node
    volumes:
      - '${LOCAL_DATA_DIR}:/usr/share/elasticsearch/data'
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - '5601:5601'
    networks:
      - bookmark

networks:
  bookmark:
    driver: bridge
